### ISSUE TITLE
RTMP url max length

### ISSUE THREAD

**Issue by Chocolladin** [NodeMedia/react-native-nodemediaclient#104]
Hello, iam using nodemediaclient for streaming app and i am authenticating with a long firebase token. My url get truncated on publish and thus all token are wrong. is there a way to increase the max size of the sent rtmp url ? 

exemple of url with token : 
rtmp://mystreamingserver:1935/live/demox_545?token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFmMDg2ZmE4Y2Q5NDFlMDY3ZTc3NzNkYmIwNDcxMjAxMTBlMDA1NGEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20va29seS1jNDZiMiIsImF1ZCI6ImtvbHktYzQ2YjIiLCJhdXRoX3RpbWUiOjE1OTY1NzI4ODUsInVzZXJfaWQiOiI2bUJ0YTBIT0VzZHVUZUZxNFpYYndvRHRENDQzIiwic3ViIjoiNm1CdGEwSE9Fc2R1VGVGcTRaWGJ3b0R0RDQ0MyIsImlhdCI6MTU5NjYzMzE3NywiZXhwIjoxNTk2NjM2Nzc3LCJlbWFpbCI6InZhbGVyaWFuNEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidmFsZXJpYW40QGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.apHlv2f74d5hkbvFyUP5Yf1ySBrXKTvhKNNFE-jVqSI31HBs8MSlxFg8MBLOwnqJBffWsPqX_pmTVgARgUm21KuuhlEsyE5pbDzpMt_FcOASAfKOqnjMeBb-4LUJe8yPNFsCI9Nxo6D878Ci6I1V8fp3oReIclGBAKOMkOCx6KKyprqsWFs0KqEc1ikAoa3PAQb6kV9--4hjTr8yumoqZ-DqhhTwrl9-FTCx4vw-x35d9sAp3TI8mE8wfNhjb4AAF3-PBYVA2De_y6bndh8NUCZ3m5Gck_u6NFZBWFWu29lWP70LHKz33gG8dveSEOqWc8MI2qzAq7xm-a43Tz_T-g

regards, 

Bertrand

**Comment by illuspas** [comment]
Try to update version V0.2.7

**Comment by Chocolladin** [comment]
Hi, thanks for your reply. i updated to 0.2.7 still same issue : 

log for nginx rtmp module : 

192.168.1.1 [11/Aug/2020:10:19:29 +0100] PUBLISH "live" "demox_132" "token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFmMDg2ZmE4Y2Q5NDFlMDY3ZTc3NzNkYmIwNDcxMjAxMTBlMDA1NGEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20va29seS1jNDZiMiIsImF1ZCI6ImtvbHktYzQ2YjIiLCJhdXRoX3RpbWUiOjE1OTY1NzI4ODUsInVzZXJfaWQiOiI2bUJ0YTBIT0VzZHVUZUZxNFpYYndvRHRENDQzIiwic3ViIjoiNm1CdGEwSE9Fc2R1VGVGcTRaWGJ3b0R0RDQ0MyIsImlhdCI6MTU5NjYzMzE3NywiZXhwIjoxNTk2NjM2Nzc3LCJlbWFpbCI6InZhbGVyaWFuNEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsi" - 1871 1109 "" "FMLE/3.0 (compatible; Lavf58.20" (0s)

the token gets truncated at  xxxW1haWwiOlsi...

Regards, 

Bertrand

**Comment by illuspas** [comment]
I continued to track the code and found that the underlying library limited the maximum length.
I will fix this in the next version.

**Comment by illuspas** [comment]
Try to update version V0.2.8

**Comment by Chocolladin** [comment]
Good evening, i updated to V0.2.8 and issue was fixed. My URL is now sent completly to server. :) 

Thanks a lot for your help and your reactivity, 

regards, Bertrand.
