### ISSUE TITLE
keep getting a nodeclient media when i try to build for ios

### ISSUE THREAD

**Issue by frank505** [NodeMedia/react-native-nodemediaclient#105]
"___darwin_check_fd_set_overflow", referenced from:
      _kmp_read in NodeMediaClient(kmp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by TalhaArshad** [comment]
> "___darwin_check_fd_set_overflow", referenced from:
> _kmp_read in NodeMediaClient(kmp.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by TalhaArshad** [comment]
I am facing same issue. Any success?

**Comment by illuspas** [comment]
Xcode version ?

**Comment by TalhaArshad** [comment]
> Xcode version ?

it's 11.2.1

**Comment by frank505** [comment]
mine is version 11.3

**Comment by snobear** [comment]
Per #94 this error is fixed if you upgrade to xcode >= 11.5. I haven't tried this yet myself...first I need to upgrade to Catalina in order to upgrade Xcode.

**Comment by frank505** [comment]
if this is true then i will try that this weekend

**Comment by frank505** [comment]
i am closing this issue @snobear thanks i do appreciate :)

**Comment by RupamShaw** [comment]
same issue with xcode 12 macos catalina 10.15.6, App builds in iphone device . Its not building in any of the simulator.
