### ISSUE TITLE
Is the Free Edition still available?

### ISSUE THREAD

**Issue by ishanAhuja** [NodeMedia/react-native-nodemediaclient#134]
Hi.

On the latest version (0.2.14), when mounting the ```NodeCameraView``` component, I am seeing the following messages in my iOS debug log: ```NodePublisher init with Pro Edition``` and ```NetConnection.Connect.Failed [-5] (Input/output error)```. The streaming is not starting as it did earlier. 

I noticed that the debug log earlier used to say ```NodePublisher init with Free Edition```, and I wanted to know if there is something in my code causing the Pro/Premium edition to be used? If so, how may I continue using the Free edition as before?

JSX snippet of my ```NodeCameraView``` component:
```jsx
<NodeCameraView
  ref={vb => {
    this.vb = vb;
  }}
  outputUrl={this.state.ingestUrl + '/cast'}
  camera={{cameraId: 1, cameraFrontMirror: true}}
  audio={{bitrate: 32000, profile: 1, samplerate: 44100}}
  video={{
    bitrate: 3584000,
    preset: 4,
    profile: 1,
    fps: 30,
    videoFrontMirror: false,
  }}
  denoise={false}
  autopreview={true}
/>
```

Thanks!

**Comment by jwstanly** [comment]
I've been using the free version just fine over the last couple weeks on iOS and Android. I'm using all those NodeCameraView props as well. Maybe this error message is being thrown for something else? I'm not sure exactly; I haven't read any of the source code yet.

**Comment by frank505** [comment]
@jwstanly you have been using it for both android and ios and it works just fine, please i am currently having some issues with the microphone playing the audio stream on IOS any advice?

**Comment by ishanAhuja** [comment]
Deleting and recreating the CocoaPods directory fixed this for me. Maybe the native code had gotten out of sync for some reason. Closing this issue.
