### ISSUE TITLE
I am getting NetStream.Buffer.Full event but video still freezed

### ISSUE THREAD

**Issue by alimoncul** [NodeMedia/react-native-nodemediaclient#135]
I am stopping the stream publish for 10 seconds and after that I continue to publish stream. The viewer receives events below but the player doesn't play the video/audio. It waits like 2-3 minutes then It starts playing the video/audio.

{"event":1101,"message":"NetStream.Buffer.Buffering"}
{"event":1102,"message":"NetStream.Buffer.Full"}

**Comment by frank505** [comment]
@alimoncul  is this on android or ios or both?

**Comment by alimoncul** [comment]
both os
