### ISSUE TITLE
Video has been crop on every where.

### ISSUE THREAD

**Issue by codal-mpawar** [NodeMedia/react-native-nodemediaclient#141]
Hi,

I am using the latest version of this library. but I am getting one issue is video cropping. so anyone has an idea about that please help me with this. I am using NodeCameraView and its style is {flex:1}. scaleMode='ScaleAspectFit'

<NodeCameraView
style={{flex:1}}
ref={this.props.getVideoRef}
outputUrl={
	url
}
camera={{ cameraId: 1, cameraFrontMirror: true }}
audio={{ bitrate: 32000, profile: 1, samplerate: 44100 }}
scaleMode='ScaleAspectFit'
video={{
	preset: 12,
	bitrate: 400000,
	profile: 1,
	fps: 15,
	videoFrontMirror: false
}}
autopreview={true}
/>

-

**Comment by codal-mpawar** [comment]
Resolve issue self. if any one need solution please look at this example

const config = {
	cameraConfig: {
		cameraId: 1,
		cameraFrontMirror: false
	},
	videoConfig: {
		preset: 4,
		bitrate: 2000000,
		profile: 2,
		fps: 30,
		videoFrontMirror: true
	},
	audioConfig: {
		bitrate: 128000,
		profile: 1,
		samplerate: 44100
	}
};

<NodeCameraView
style={styles.nodeCameraContainer}
ref={this.props.getVideoRef}
outputUrl={
	url
}
camera={config.cameraConfig}
audio={config.audioConfig}
video={config.videoConfig}
autopreview={true}
/>

**Comment by cuonggosu97** [comment]
Can you tell me the components of styles.nodeCameraContainer? Thank you!

**Comment by codal-mpawar** [comment]
const { width, height } = Dimensions.get('window');
nodeCameraContainer: { width, height }

this is my style

**Comment by codal-mpawar** [comment]
@cuonggosu97 

> const { width, height } = Dimensions.get('window');
> nodeCameraContainer: { width, height }
> 
> this is my style
