### ISSUE TITLE
onStatus event handling

### ISSUE THREAD

**Issue by kiambote** [NodeMedia/react-native-nodemediaclient#143]
Hi all, I went several times to try to understand how onStatus works. When does the event fires ? 

Is it only when we call the methods play() and stop() ? 
Is it when the connection with the RTMP server is lost for example ?

I am trying to implement a reconnect method relaying on onStatus.

**Comment by bgabrielma** [comment]
Hey @kiambote, I am using onStatus to debug the flow.
onStatus is triggered whenever you have the following status:

// 2000 - Connecting
// 2001 - Start publishing
// 2002 - Connection failed (input/output) error
// 2004 - Connection closed
// 2100 - Publish network congestion

Example syntax: onStatus={(code, message) => console.log(code, message)}

- Using the .start() and .stop() function will trigger 2000, 2001 and 2004. When you switch between WiFi and your mobile internet, on reconnecting, you could get an 2100 as well.

Hope this is helpful to your question.

Regards,
bgabrielma

**Comment by kiambote** [comment]
Whow! @bgabrielma that is very helpful, thank you!

**Comment by sstatsuya** [comment]
> Hey @kiambote, I am using onStatus to debug the flow in a specific project of mine. onStatus is triggered whenever you have, for example, these following status:
> 
> // 2000 - Connecting // 2001 - Start publishing // 2002 - Connection failed (input/output) error // 2004 - Connection closed // 2100 - Publish network congestion
> 
> Example syntax: onStatus={(code, message) => console.log(code, message)}
> 
> * Using the .start() and .stop() function will trigger 2000, 2001 and 2004. When you switch between WiFi and your mobile internet, on reconnecting, you could get an 2100 as well.
> 
> Hope this is helpful to your question.
> 
> Regards, bgabrielma

Where do you get this error code list? Can I get it.
