### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by AleksandrVais** [NodeMedia/react-native-nodemediaclient#144]
When I run my project on Android everything was fine. But when I use a real iOS device or emulator, I get a white screen. All permissions received. How can I fix it?

Xcode 12.4
MacOS Big Sur
iPhone 11 emulator with iOS 13.6
iPhone Xr with iOS 14.4

**Comment by gessic-apps** [comment]
did you figure it out @AleksandrVais ?

**Comment by bachbonglong** [comment]
Me too . How did you solve it ? @AleksandrVais

**Comment by AleksandrVais** [comment]
@bachbonglong , @gessic-apps Use classes component instead functional to camera. (As  in tutorial)
