### ISSUE TITLE
Android: Second time camera not working displaying black screen.

### ISSUE THREAD

**Issue by codal-mpawar** [NodeMedia/react-native-nodemediaclient#163]
@illuspas 
@matinzd 
@Andriiklymiuk 
@lethienhung 

Hey guys,
I am facing issue in android.
When i start streaming first time camera working fine. but when i start again after 2 or 3 minute its showing me a black screen. its not freez or not crash.

Help me on that I am block here!

Thank you.

**Comment by pradeeptry** [comment]
i am also facing same issue on android.
