### ISSUE TITLE
cool, it's work!

### ISSUE THREAD

**Issue by teilala** [NodeMedia/react-native-nodemediaclient#2]
it's work, amazing!
我試過所有的rtmp、rtsp、vlc、ijk、
只有你的支持android、ios ，而且還可以work!!
thank you ~

**Comment by mkrn** [comment]
Amazing!  How can this be connected with USB UVC camera?
Like with some package like this - https://github.com/flyskywhy/react-native-uvc-camera ?

Thanks!

**Comment by teilala** [comment]
I have no idea maybe you can try it with yourself

**Comment by CocktailZY** [comment]
> 惊人！如何与USB UVC相机连接？
> 像这样的一些包 - https://github.com/flyskywhy/react-native-uvc-camera？
> 
> 谢谢！
Has UVC Camera Access been Successful?


> Amazing! How can this be connected with USB UVC camera?
> Like with some package like this - https://github.com/flyskywhy/react-native-uvc-camera ?
> 
> Thanks!

Has UVC Camera connected been successful?
