### ISSUE TITLE
Error generating apk

### ISSUE THREAD

**Issue by thxmxx** [NodeMedia/react-native-nodemediaclient#21]
* What went wrong:
Execution failed for task ':react-native-nodemediaclient:verifyReleaseResources'.

**Comment by vigikaran** [comment]
Run the below command and try again.
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && react-native run-android`

**Comment by johntzan** [comment]
``` 
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```
Adding this to my app/build.gradle fixed it for me

**Comment by smileyqp** [comment]
> ```
> subprojects {
>     afterEvaluate {project ->
>         if (project.hasProperty("android")) {
>             android {
>                 compileSdkVersion rootProject.ext.compileSdkVersion
>                 buildToolsVersion rootProject.ext.buildToolsVersion
>             }
>         }
>     }
> }
> ```
> 
> Adding this to my android/build.gradle fixed it for me

this works

**Comment by prem-tcpl** [comment]
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}




it works Thanks :100:

**Comment by iamabdulhaseeb** [comment]
> ```
> subprojects {
>     afterEvaluate {project ->
>         if (project.hasProperty("android")) {
>             android {
>                 compileSdkVersion rootProject.ext.compileSdkVersion
>                 buildToolsVersion rootProject.ext.buildToolsVersion
>             }
>         }
>     }
> }
> ```
> 
> Adding this to my android/build.gradle fixed it for me

It Works! thank you.
