### ISSUE TITLE
Stream audio only

### ISSUE THREAD

**Issue by harrymelka** [NodeMedia/react-native-nodemediaclient#4]
Hello,

is there a way to stream audio only ? I tried multiple solutions but nothing worked I still have videos on the stream feed.

I try to use ffmpeg to extract audio and restream it but still not working.

Thank you

**Comment by illuspas** [comment]
Update to 0.3.4, remove videoParam and you'll be able to do audio-only live streaming.

**Comment by harrymelka** [comment]
Thank you @illuspas I m going to try that !
