### ISSUE TITLE
按步骤项目运行总是会报linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by guotingchaopr** [NodeMedia/react-native-nodemediaclient#5]
![image](https://user-images.githubusercontent.com/2443075/40302569-18f1b9f0-5d22-11e8-8225-bfad2157df8e.png)

**Comment by BinniZenobioCordovaLeandro** [comment]
same here:
linker command failed with exit code 1
<img width="943" alt="Captura de Pantalla 2020-09-21 a la(s) 18 19 17" src="https://user-images.githubusercontent.com/42467277/93830842-f78f0400-fc36-11ea-96b3-7182db1ccea9.png">
