### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RCTNodeCamera" was not found in the UIManager.

### ISSUE THREAD

**Issue by nghianvbsc** [NodeMedia/react-native-nodemediaclient#57]
![Simulator Screen Shot - iPhone 8 - 2019-11-06 at 09 52 15](https://user-images.githubusercontent.com/19502056/68264395-495c8900-007b-11ea-810f-91a94cbd68c6.png)

Error on react native 0.61.4

**Comment by lok225** [comment]
@nghianvbsc  What did you do to solve it?

**Comment by nghianvbsc** [comment]
> @nghianvbsc What did you do to solve it?

@lok225  in react native >0.6, don't run react-native link, and open xcode remove this lib .a

watch video: https://www.youtube.com/watch?v=augnjPRuBy0

**Comment by lok225** [comment]
@nghianvbsc Thank you ! It worked

**Comment by jrfurini** [comment]
@nghianvbsc Thank you, your video help me so much.
