### ISSUE TITLE
android broadcast using back cemera id 0, white screen

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [NodeMedia/react-native-nodemediaclient#70]
android broadcast using back cemera id 0, white screen. I tested using samsung galaxy s10 +, when set the cameraId to 0, the camera screen is white and not streaming any data

**Comment by graffme** [comment]
@ManigandanRaamanathan You have to ask user about permissions, otherwise you will see empty view. Please look at this solution:
https://github.com/Syntx-io/RN-Livestream-Example

**Comment by ManigandanRaamanathan** [comment]
fixed using `this.vb.switchCamera()`
