### ISSUE TITLE
Android not mounting camera's when switch between front and back camera

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [NodeMedia/react-native-nodemediaclient#75]
@illuspas Android not mounting camera's when switch between front and back camera. The screen goes white when switch from camera type from one another. I guess its not unmounting from current camera and to mount the new camera type. 

props used for front camera:-
`camera={{cameraId: 1, cameraFrontMirror: true}}`

props used for back camera:-
`camera={{cameraId: 0, cameraFrontMirror: false}}`

this camera type conflicts with the react-native-camera as well. If the type set to a particular type of camera and then react-native-camera launch different camera type in react-native-camera causes both camera return nothing.

**Comment by ManigandanRaamanathan** [comment]
fixed using `this.vb.switchCamera()`

**Comment by govind1530** [comment]
can you share the code?

**Comment by ManigandanRaamanathan** [comment]
> can you share the code?

@govind1530 just call the reference method switchCamera()

**Comment by govind1530** [comment]
@ManigandanRaamanathan  thanks its work
