### ISSUE TITLE
美颜不起作用

### ISSUE THREAD

**Issue by qiongyue** [NodeMedia/react-native-nodemediaclient#81]
设置了smoothSkinLevel 参数，分别设置为0,5没见到有变化？

**Comment by zzkkss** [comment]
> 设置了smoothSkinLevel 参数，分别设置为0,5没见到有变化？

麻烦问一下，你怎么解决的啊？

**Comment by qiongyue** [comment]
> > 设置了smoothSkinLevel 参数，分别设置为0,5没见到有变化？
> 
> 麻烦问一下，你怎么解决的啊？

这是高级版功能，需要付费购买license才能开启
